### ISSUE TITLE
added label 

### ISSUE THREAD

**Issue by brianteeman** [philschatz/project-bot#11] opened 2018-08-17 16:49 UTC
Hi 

I am trying to set this bot up for the official Joomla repository here https://github.com/joomla/joomla-cms/projects/13

The bot is working because I successfully tested the rule `new_issue`

However I am unsuccessful in getting the bot to work with the rule `added_label`

``- `added_label` **J3**
``

Am I missing something obvious?

**Comment by philschatz** [comment] 2018-08-21 14:33
It looks like that should work. Can you try it without the bold? I just tried adding (& removing) the `wontfix` label and this Issue correctly moved.

```
- `added_label` J3
```

**Comment by brianteeman** [comment] 2018-08-21 14:46
Sadly that didnt work either

![image](https://user-images.githubusercontent.com/1296369/44408883-2ec2f080-a559-11e8-899a-788388adb245.png)

**Comment by janpio** [comment] 2018-09-20 12:54
I had/have similar issues with this, but it worked on an empty project board. Have you tried that @brianteeman? If you like, you can read about my testing over at https://github.com/philschatz/project-bot/issues/17

**Comment by brianteeman** [comment] 2018-09-20 12:59
My tests were not an empty board in the sense that the board was created with one of the templates. I will try again following your tests and see if that fixes it - thanks

**Comment by saerdnaer** [comment] 2018-09-23 17:15
The problem is that the issue has already to be on the board, before the `added_label` action works for this issue. You can add an issue to an board e.g. via an 'inbox' column with the `new_issue` action.

**Comment by janpio** [comment] 2018-09-23 19:03
Was not the issue in my case, I was experimenting with issues that were already on the board or new issues I created and then added a label.

**Closed** 2020-04-04 08:52 UTC
